# Generated by Django 3.2.9 on 2021-11-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_senna_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senna',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='senna',
            name='img',
            field=models.TextField(),
        ),
    ]
