# Generated by Django 3.2.9 on 2021-11-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_alter_senna_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senna',
            name='name',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
