# Generated by Django 3.2.9 on 2021-11-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_senna_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senna',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='senna',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
