# Generated by Django 3.2.9 on 2021-11-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_pregunta_senna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senna',
            name='img',
            field=models.TimeField(),
        ),
    ]
