# Generated by Django 3.2.9 on 2021-11-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_alter_senna_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senna',
            name='img',
            field=models.TextField(),
        ),
    ]
